services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: ""
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        value: "8055049662:AAFJMynrX0hyP1XZtsaVT97P5zutbjAN4No"
